# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summoner_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
