# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160508_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='server',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
